"""AI Safety Confidence Thresholds.

Refuses to present clinical predictions when model confidence is dangerously low.
All outputs include mandatory medical disclaimers.
"""
import logging
import os
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)

MINIMUM_CONFIDENCE_THRESHOLD = float(os.getenv("AI_MIN_CONFIDENCE", "0.15"))
HIGH_RISK_CONFIDENCE_THRESHOLD = float(os.getenv("AI_HIGH_RISK_CONFIDENCE", "0.30"))

SAFETY_DISCLAIMER = (
    "⚠️ Medical Disclaimer: This prediction is generated by an AI system for "
    "informational purposes only. It is NOT a substitute for professional medical "
    "judgment. Please consult a qualified clinician for diagnosis, treatment, or emergencies."
)

LOW_CONFIDENCE_WARNING = (
    "⚠️ LOW CONFIDENCE WARNING: The AI model's confidence for this prediction is below "
    "the safety threshold. This result should be treated with extreme caution and verified "
    "by a qualified medical professional before any clinical decision is made."
)

@dataclass
class SafetyVerdict:
    safe_to_present: bool
    confidence: float
    risk_level: str
    warning: Optional[str] = None
    disclaimer: str = SAFETY_DISCLAIMER
    requires_clinician_review: bool = True

def check_prediction_safety(
    confidence: float,
    risk_level: str = "unknown",
) -> SafetyVerdict:
    if confidence < MINIMUM_CONFIDENCE_THRESHOLD:
        logger.warning(
            "AI prediction below minimum confidence threshold: %.3f < %.3f",
            confidence, MINIMUM_CONFIDENCE_THRESHOLD
        )
        return SafetyVerdict(
            safe_to_present=False,
            confidence=confidence,
            risk_level=risk_level,
            warning=LOW_CONFIDENCE_WARNING,
            requires_clinician_review=True,
        )

    warning = None
    if risk_level in ("high", "critical") and confidence < HIGH_RISK_CONFIDENCE_THRESHOLD:
        warning = (
            f"⚠️ ELEVATED CAUTION: High-risk prediction ({risk_level}) with moderate confidence "
            f"({confidence:.1%}). Clinician verification is strongly recommended."
        )
        logger.warning("High-risk prediction with moderate confidence: %.3f", confidence)

    return SafetyVerdict(
        safe_to_present=True,
        confidence=confidence,
        risk_level=risk_level,
        warning=warning,
        requires_clinician_review=risk_level in ("high", "critical"),
    )

def get_safety_config() -> dict:
    return {
        "minimum_confidence_threshold": MINIMUM_CONFIDENCE_THRESHOLD,
        "high_risk_confidence_threshold": HIGH_RISK_CONFIDENCE_THRESHOLD,
        "safety_disclaimer_active": True,
        "low_confidence_blocking_enabled": True,
        "sota_guardrails_active": True,
    }


def inspect_clinical_guardrails(prompt_text: str, response_text: str) -> dict:
    """
    SOTA Clinical Guardrail Evaluator (NeMo Guardrails & Llama-Guard Clinical pattern).
    Audits prompt and candidate LLM output for toxic instruction injection, dangerous drug dosage bounds,
    and medical disclaimer compliance.
    """
    combined = (prompt_text + " " + response_text).lower()
    violations = []
    blocked = False

    # 1. Dangerous instruction / jailbreak check
    jailbreak_keywords = ["ignore previous instructions", "act as an unlicensed doctor", "override safety protocols"]
    if any(kw in combined for kw in jailbreak_keywords):
        violations.append("Adversarial prompt injection or safety override attempt detected.")
        blocked = True

    # 2. Extreme drug dosage anomaly check (e.g. >2000mg Metformin, >100mg Lisinopril, >1000mg Aspirin single dose)
    import re
    dosages = re.findall(r'(\d+)\s*(mg|grams|g)', response_text, re.IGNORECASE)
    for amount_str, unit in dosages:
        amount = int(amount_str)
        if unit.lower() in ('g', 'grams') and amount > 5:
            violations.append(f"Potentially toxic single dose detected ({amount} {unit}). Max threshold exceeded.")
            blocked = True
        elif unit.lower() == 'mg' and amount > 4000:
            violations.append(f"Potentially toxic single mg dose detected ({amount} mg). Max threshold exceeded.")
            blocked = True

    # 3. Emergency protocol reminder
    emergency_symptoms = ["chest pain", "shortness of breath", "anaphylaxis", "sudden numbness"]
    requires_emergency_flag = any(sym in combined for sym in emergency_symptoms)

    return {
        "passed": not blocked,
        "violations": violations,
        "emergency_symptom_flag": requires_emergency_flag,
        "guardrail_status": "BLOCKED" if blocked else ("PASSED" if not violations else "WARNING"),
        "disclaimer": SAFETY_DISCLAIMER
    }

