"""AI Safety Confidence Thresholds.

Refuses to present clinical predictions when model confidence is dangerously low.
All outputs include mandatory medical disclaimers.
"""
import logging
import os
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)

MINIMUM_CONFIDENCE_THRESHOLD = float(os.getenv("AI_MIN_CONFIDENCE", "0.15"))
HIGH_RISK_CONFIDENCE_THRESHOLD = float(os.getenv("AI_HIGH_RISK_CONFIDENCE", "0.30"))

SAFETY_DISCLAIMER = (
    "⚠️ Medical Disclaimer: This prediction is generated by an AI system for "
    "informational purposes only. It is NOT a substitute for professional medical "
    "judgment. Please consult a qualified clinician for diagnosis, treatment, or emergencies."
)

LOW_CONFIDENCE_WARNING = (
    "⚠️ LOW CONFIDENCE WARNING: The AI model's confidence for this prediction is below "
    "the safety threshold. This result should be treated with extreme caution and verified "
    "by a qualified medical professional before any clinical decision is made."
)

@dataclass
class SafetyVerdict:
    safe_to_present: bool
    confidence: float
    risk_level: str
    warning: Optional[str] = None
    disclaimer: str = SAFETY_DISCLAIMER
    requires_clinician_review: bool = True

def check_prediction_safety(
    confidence: float,
    risk_level: str = "unknown",
) -> SafetyVerdict:
    if confidence < MINIMUM_CONFIDENCE_THRESHOLD:
        logger.warning(
            "AI prediction below minimum confidence threshold: %.3f < %.3f",
            confidence, MINIMUM_CONFIDENCE_THRESHOLD
        )
        return SafetyVerdict(
            safe_to_present=False,
            confidence=confidence,
            risk_level=risk_level,
            warning=LOW_CONFIDENCE_WARNING,
            requires_clinician_review=True,
        )

    warning = None
    if risk_level in ("high", "critical") and confidence < HIGH_RISK_CONFIDENCE_THRESHOLD:
        warning = (
            f"⚠️ ELEVATED CAUTION: High-risk prediction ({risk_level}) with moderate confidence "
            f"({confidence:.1%}). Clinician verification is strongly recommended."
        )
        logger.warning("High-risk prediction with moderate confidence: %.3f", confidence)

    return SafetyVerdict(
        safe_to_present=True,
        confidence=confidence,
        risk_level=risk_level,
        warning=warning,
        requires_clinician_review=risk_level in ("high", "critical"),
    )

def get_safety_config() -> dict:
    return {
        "minimum_confidence_threshold": MINIMUM_CONFIDENCE_THRESHOLD,
        "high_risk_confidence_threshold": HIGH_RISK_CONFIDENCE_THRESHOLD,
        "safety_disclaimer_active": True,
        "low_confidence_blocking_enabled": True,
    }
