/**
 * Generate tool-specific adapter files from a shared manifest — Bun Native TypeScript Implementation.
 * 
 * Canonical human-authored policy lives in:
 * - AGENTS.md
 * - scoped AGENTS.md files
 * 
 * Run:
 *     bun scripts/sync_agent_adapters.ts
 *     bun scripts/sync_agent_adapters.ts --check
 */

import { readFileSync, writeFileSync, unlinkSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const MANIFEST_PATH = resolve(ROOT, 'scripts', 'agent_adapter_manifest.json');
const GENERATED_NOTE = '<!-- Generated by scripts/sync_agent_adapters.py from scripts/agent_adapter_manifest.json. Do not edit manually. -->';

function loadManifest(): any {
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));
}

function lines(items: string[]): string {
  return items.map((i) => `- ${i}`).join('\n');
}

function cursorYamlList(items: string[]): string {
  return items.map((i) => `  - "${i}"`).join('\n');
}

function renderWrapper(pathName: string, repoName: string, target: string): string {
  return [
    GENERATED_NOTE,
    `# ${pathName} - ${repoName}`,
    '',
    `@./${target}`,
    '',
  ].join('\n');
}

function renderScopedWrapper(pathName: string, repoName: string, targets: string[]): string {
  return [
    GENERATED_NOTE,
    `# ${pathName} - ${repoName}`,
    '',
    ...targets.map((t) => `@${t}`),
    '',
  ].join('\n');
}

function renderCursorrules(l: string[]): string {
  return [
    GENERATED_NOTE,
    '# AI Healthcare System - Cursor Compatibility Shim',
    '',
    lines(l),
    '',
  ].join('\n');
}

function renderCopilotRepo(repoName: string, l: string[]): string {
  return [
    GENERATED_NOTE,
    `# ${repoName} - Repository Instructions`,
    '',
    lines(l),
    '',
  ].join('\n');
}

function renderCopilotScope(applyTo: string, l: string[]): string {
  return [
    '---',
    `applyTo: "${applyTo}"`,
    '---',
    GENERATED_NOTE,
    lines(l),
    '',
  ].join('\n');
}

function renderCursorRule(description: string, globs: string[], l: string[], refs: string[]): string {
  return [
    '---',
    `description: ${description}`,
    'alwaysApply: false',
    'globs:',
    cursorYamlList(globs),
    '---',
    GENERATED_NOTE,
    '',
    ...l,
    '',
    ...refs.map((r) => `@${r}`),
    '',
  ].join('\n');
}

function renderCursorRootRule(description: string, l: string[], refs: string[]): string {
  return [
    '---',
    `description: ${description}`,
    'alwaysApply: true',
    '---',
    GENERATED_NOTE,
    '',
    ...l,
    '',
    ...refs.map((r) => `@${r}`),
    '',
  ].join('\n');
}

function renderKiroFile(title: string, l: string[]): string {
  return [
    '---',
    'inclusion: always',
    '---',
    GENERATED_NOTE,
    '',
    `# ${title}`,
    '',
    '- Canonical coding instructions live in AGENTS.md; also read the nearest scoped AGENTS.md before editing files.',
    '',
    lines(l),
    '',
  ].join('\n');
}

function buildGeneratedFiles(manifest: any): Record<string, string> {
  const files: Record<string, string> = {};
  const repoName = manifest.repo_name;
  const target = manifest.canonical_agents_file;

  for (const wrapper of manifest.wrapper_files) {
    files[wrapper] = renderWrapper(wrapper, repoName, target);
  }

  for (const wrapper of manifest.scoped_wrapper_files || []) {
    files[wrapper.path] = renderScopedWrapper(wrapper.path, repoName, wrapper.targets);
  }

  files['.cursorrules'] = renderCursorrules(manifest.cursor_legacy_shim_lines);
  files['.github/copilot-instructions.md'] = renderCopilotRepo(repoName, manifest.copilot_repo_lines);

  const cursorRoot = manifest.cursor_root_rule;
  files['.cursor/rules/00-root.mdc'] = renderCursorRootRule(
    cursorRoot.description,
    cursorRoot.lines,
    cursorRoot.refs
  );

  for (const scope of manifest.scopes) {
    files[`.github/instructions/${scope.id}.instructions.md`] = renderCopilotScope(
      scope.copilot_apply_to,
      scope.copilot_lines
    );
    files[`.cursor/rules/${scope.cursor_rule_file}`] = renderCursorRule(
      scope.cursor_description,
      scope.cursor_globs,
      scope.cursor_lines,
      scope.cursor_refs
    );
  }

  files['.kiro/steering/product.md'] = renderKiroFile('Product Overview', manifest.kiro.product);
  files['.kiro/steering/tech.md'] = renderKiroFile('Technology Stack', manifest.kiro.tech);
  files['.kiro/steering/structure.md'] = renderKiroFile('Project Structure', manifest.kiro.structure);

  return files;
}

function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');

  const manifest = loadManifest();
  const files = buildGeneratedFiles(manifest);

  if (checkOnly) {
    const errors: string[] = [];
    const normalize = (s: string) => s.replace(/\r\n/g, '\n').trim();
    for (const [relPath, expected] of Object.entries(files)) {
      const full = resolve(ROOT, relPath);
      if (!existsSync(full)) {
        errors.push(`missing generated file: ${relPath}`);
        continue;
      }
      const actual = readFileSync(full, 'utf-8');
      if (normalize(actual) !== normalize(expected)) {
        errors.push(`out-of-sync generated file: ${relPath}`);
      }
    }

    if (errors.length > 0) {
      console.log('Agent adapter sync: FAIL');
      for (const err of errors) {
        console.log(` - ${err}`);
      }
      process.exit(1);
    }

    console.log('Agent adapter sync: PASS');
    console.log(` - generated files in sync: ${Object.keys(files).length}`);
    process.exit(0);
  }

  for (const [relPath, content] of Object.entries(files)) {
    const full = resolve(ROOT, relPath);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, content, 'utf-8');
  }

  for (const obsolete of manifest.obsolete_files || []) {
    const full = resolve(ROOT, obsolete);
    if (existsSync(full)) {
      unlinkSync(full);
    }
  }

  console.log('Agent adapter sync: WROTE');
  console.log(` - generated files written: ${Object.keys(files).length}`);
}

main();
