"""Initial schema

Revision ID: 275039c926c9
Revises:
Create Date: 2026-06-06 19:44:19.704842

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '275039c926c9'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admissions_facility_id'), 'admissions', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'admissions', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_appointments_facility_id'), 'appointments', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_facility_id'), 'audit_logs', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_beds_facility_id'), 'beds', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'beds', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_billable_services_facility_id'), 'billable_services', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'billable_services', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_billing_payments_facility_id'), 'billing_payments', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'billing_payments', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_care_events_facility_id'), 'care_events', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'care_events', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_clinical_orders_facility_id'), 'clinical_orders', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'clinical_orders', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_departments_facility_id'), 'departments', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_diagnostic_results_facility_id'), 'diagnostic_results', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'diagnostic_results', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_discharge_summaries_facility_id'), 'discharge_summaries', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'discharge_summaries', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_dispense_records_facility_id'), 'dispense_records', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'dispense_records', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_encounters_facility_id'), 'encounters', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'encounters', 'hospital_facilities', ['facility_id'], ['id'])
    op.alter_column('interoperability_consents', 'abdm_last_event_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_interoperability_consents_abdm_consent_id'), 'interoperability_consents', ['abdm_consent_id'], unique=False)
    op.create_index(op.f('ix_interoperability_consents_abdm_request_id'), 'interoperability_consents', ['abdm_request_id'], unique=False)
    op.create_index(op.f('ix_interoperability_consents_facility_id'), 'interoperability_consents', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'interoperability_consents', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_interoperability_export_profiles_facility_id'), 'interoperability_export_profiles', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'interoperability_export_profiles', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_interoperability_exports_facility_id'), 'interoperability_exports', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'interoperability_exports', 'interoperability_export_profiles', ['profile_id'], ['id'])
    op.create_foreign_key(None, 'interoperability_exports', 'interoperability_consents', ['consent_id'], ['id'])
    op.create_foreign_key(None, 'interoperability_exports', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_invoices_facility_id'), 'invoices', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_medication_inventory_facility_id'), 'medication_inventory', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'medication_inventory', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_monitoring_signals_facility_id'), 'monitoring_signals', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'monitoring_signals', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_nursing_tasks_facility_id'), 'nursing_tasks', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'nursing_tasks', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_prescriptions_facility_id'), 'prescriptions', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'prescriptions', 'hospital_facilities', ['facility_id'], ['id'])
    op.create_index(op.f('ix_users_facility_id'), 'users', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'users', 'hospital_facilities', ['facility_id'], ['id'])
    op.drop_column('users', 'doctor_id')
    op.create_index(op.f('ix_vital_observations_facility_id'), 'vital_observations', ['facility_id'], unique=False)
    op.create_foreign_key(None, 'vital_observations', 'hospital_facilities', ['facility_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vital_observations', type_='foreignkey')
    op.drop_index(op.f('ix_vital_observations_facility_id'), table_name='vital_observations')
    op.add_column('users', sa.Column('doctor_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_facility_id'), table_name='users')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_index(op.f('ix_prescriptions_facility_id'), table_name='prescriptions')
    op.drop_constraint(None, 'nursing_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_nursing_tasks_facility_id'), table_name='nursing_tasks')
    op.drop_constraint(None, 'monitoring_signals', type_='foreignkey')
    op.drop_index(op.f('ix_monitoring_signals_facility_id'), table_name='monitoring_signals')
    op.drop_constraint(None, 'medication_inventory', type_='foreignkey')
    op.drop_index(op.f('ix_medication_inventory_facility_id'), table_name='medication_inventory')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_facility_id'), table_name='invoices')
    op.drop_constraint(None, 'interoperability_exports', type_='foreignkey')
    op.drop_constraint(None, 'interoperability_exports', type_='foreignkey')
    op.drop_constraint(None, 'interoperability_exports', type_='foreignkey')
    op.drop_index(op.f('ix_interoperability_exports_facility_id'), table_name='interoperability_exports')
    op.drop_constraint(None, 'interoperability_export_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_interoperability_export_profiles_facility_id'), table_name='interoperability_export_profiles')
    op.drop_constraint(None, 'interoperability_consents', type_='foreignkey')
    op.drop_index(op.f('ix_interoperability_consents_facility_id'), table_name='interoperability_consents')
    op.drop_index(op.f('ix_interoperability_consents_abdm_request_id'), table_name='interoperability_consents')
    op.drop_index(op.f('ix_interoperability_consents_abdm_consent_id'), table_name='interoperability_consents')
    op.alter_column('interoperability_consents', 'abdm_last_event_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_index(op.f('ix_encounters_facility_id'), table_name='encounters')
    op.drop_constraint(None, 'dispense_records', type_='foreignkey')
    op.drop_index(op.f('ix_dispense_records_facility_id'), table_name='dispense_records')
    op.drop_constraint(None, 'discharge_summaries', type_='foreignkey')
    op.drop_index(op.f('ix_discharge_summaries_facility_id'), table_name='discharge_summaries')
    op.drop_constraint(None, 'diagnostic_results', type_='foreignkey')
    op.drop_index(op.f('ix_diagnostic_results_facility_id'), table_name='diagnostic_results')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index(op.f('ix_departments_facility_id'), table_name='departments')
    op.drop_constraint(None, 'clinical_orders', type_='foreignkey')
    op.drop_index(op.f('ix_clinical_orders_facility_id'), table_name='clinical_orders')
    op.drop_constraint(None, 'care_events', type_='foreignkey')
    op.drop_index(op.f('ix_care_events_facility_id'), table_name='care_events')
    op.drop_constraint(None, 'billing_payments', type_='foreignkey')
    op.drop_index(op.f('ix_billing_payments_facility_id'), table_name='billing_payments')
    op.drop_constraint(None, 'billable_services', type_='foreignkey')
    op.drop_index(op.f('ix_billable_services_facility_id'), table_name='billable_services')
    op.drop_constraint(None, 'beds', type_='foreignkey')
    op.drop_index(op.f('ix_beds_facility_id'), table_name='beds')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_facility_id'), table_name='audit_logs')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_facility_id'), table_name='appointments')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_index(op.f('ix_admissions_facility_id'), table_name='admissions')
    # ### end Alembic commands ###
