# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interop.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'interop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinterop.proto\x12\x07interop\"#\n\x0b\x46hirRequest\x12\x14\n\x0cjson_payload\x18\x01 \x01(\t\"D\n\x0c\x46hirResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t\"9\n\x0e\x45nclaveRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bmodel_bytes\x18\x02 \x01(\x0c\"#\n\x0f\x45nclaveResponse\x12\x10\n\x08\x61ttested\x18\x01 \x01(\x08\"d\n\x13VectorSearchRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\x11\n\tn_results\x18\x02 \x01(\x04\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x04 \x01(\t\"N\n\x0cVectorRecord\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x02\">\n\x14VectorSearchResponse\x12&\n\x07records\x18\x01 \x03(\x0b\x32\x15.interop.VectorRecord2\xdf\x01\n\x0eInteropService\x12;\n\x0cValidateFhir\x12\x14.interop.FhirRequest\x1a\x15.interop.FhirResponse\x12\x42\n\rAttestEnclave\x12\x17.interop.EnclaveRequest\x1a\x18.interop.EnclaveResponse\x12L\n\rSearchVectors\x12\x1c.interop.VectorSearchRequest\x1a\x1d.interop.VectorSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FHIRREQUEST']._serialized_start=26
  _globals['_FHIRREQUEST']._serialized_end=61
  _globals['_FHIRRESPONSE']._serialized_start=63
  _globals['_FHIRRESPONSE']._serialized_end=131
  _globals['_ENCLAVEREQUEST']._serialized_start=133
  _globals['_ENCLAVEREQUEST']._serialized_end=190
  _globals['_ENCLAVERESPONSE']._serialized_start=192
  _globals['_ENCLAVERESPONSE']._serialized_end=227
  _globals['_VECTORSEARCHREQUEST']._serialized_start=229
  _globals['_VECTORSEARCHREQUEST']._serialized_end=329
  _globals['_VECTORRECORD']._serialized_start=331
  _globals['_VECTORRECORD']._serialized_end=409
  _globals['_VECTORSEARCHRESPONSE']._serialized_start=411
  _globals['_VECTORSEARCHRESPONSE']._serialized_end=473
  _globals['_INTEROPSERVICE']._serialized_start=476
  _globals['_INTEROPSERVICE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
